# Generated by Django 4.0.5 on 2022-06-21 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='comment_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.advert', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user_reply',
            field=models.TextField(max_length=400, verbose_name='Отклик'),
        ),
    ]
