# Generated by Django 4.0.5 on 2022-06-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0003_alter_reply_comment_to_alter_reply_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'verbose_name': 'Отклик', 'verbose_name_plural': 'Отклики'},
        ),
    ]
