# Generated by Django 4.0.5 on 2022-06-29 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0004_alter_advert_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment_to',
        ),
        migrations.AddField(
            model_name='advert',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.reply', verbose_name='Отклик'),
        ),
    ]
