# Generated by Django 4.0.5 on 2022-06-30 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0005_remove_reply_comment_to_advert_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='slug',
        ),
        migrations.AddField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='advert.advert', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user_reply',
            field=models.TextField(max_length=400, null=True, verbose_name='Отклик'),
        ),
    ]
