# Generated by Django 4.0.5 on 2022-07-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0006_remove_advert_reply_remove_reply_slug_reply_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='comment',
        ),
        migrations.AddField(
            model_name='advert',
            name='reply',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='advert.reply', verbose_name='Комментрарии'),
        ),
    ]
